import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'
import Listing from '#models/listing'
import ListingPhoto from '#models/listing_photo'
import User from '#models/user'

/**
 * Demo de 40 propiedades en 8 estados/ciudades de México:
 * - CDMX: 8 (Polanco, Roma Norte, Condesa, Coyoacán, Del Valle)
 * - Mérida: 6 (Centro, Itzimná, García Ginerés)
 * - San Miguel de Allende: 4 (Centro, Atascadero)
 * - Tulum + Playa del Carmen: 6 (Aldea Zama, Selva, Playacar, Centro Playa)
 * - Querétaro: 4 (Centro, Juriquilla)
 * - Guadalajara: 4 (Providencia, Lafayette, Chapalita)
 * - Monterrey/San Pedro: 4 (San Pedro, Valle Oriente)
 * - Puerto Vallarta: 4 (Centro, Marina, Conchas Chinas)
 *
 * Idempotente vía `Listing.updateOrCreate({ slug })`. Se puede correr
 * múltiples veces sin duplicar. Asigna el primer publisher disponible
 * como agente.
 */

interface DemoListing {
  slug: string
  title: string
  summary: string
  operationType: 'venta' | 'renta_larga'
  propertyType:
    | 'casa'
    | 'departamento'
    | 'terreno'
    | 'local_comercial'
    | 'oficina'
    | 'nave_industrial'
    | 'bodega'
    | 'edificio'
  price: number
  priceLabel: string
  beds: number | null
  baths: number | null
  parking: number | null
  m2Built: number | null
  m2Land: number | null
  age: number | null
  amenities: string[]
  address: string
  zone: string
  colony: string
  municipality: string
  state: string
  lat: number
  lng: number
  isFeatured: boolean
  badges: string[]
  highlights: string[]
  photoCount: number
}

// ── CDMX (8 listings) ────────────────────────────────────────────────────
const CDMX: DemoListing[] = [
  {
    slug: 'casa-polanco-premium-vista-ciudad',
    title: 'Casa premium en Polanco con vista a la ciudad',
    summary:
      'Casa moderna de 4 recámaras en corazón de Polanco. Alberca climatizada, cine privado y terraza panorámica. Perfecta para ejecutivos.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 22500000,
    priceLabel: 'MN 22,500,000',
    beds: 4,
    baths: 4,
    parking: 3,
    m2Built: 580,
    m2Land: 420,
    age: 2,
    amenities: ['alberca', 'cine', 'terraza', 'vista_ciudad', 'seguridad_24h', 'jardin'],
    address: 'Avenida Paseo de las Palmas 555, Polanco',
    zone: 'Polanco',
    colony: 'Polanco',
    municipality: 'Cuauhtémoc',
    state: 'Ciudad de México',
    lat: 19.4330,
    lng: -99.1935,
    isFeatured: true,
    badges: ['Venta', 'Casa premium', 'Polanco'],
    highlights: ['Cine privado', 'Alberca climatizada', 'Ejecutivos'],
    photoCount: 14,
  },
  {
    slug: 'penthouse-reforma-222-lujo',
    title: 'Penthouse Reforma 222 de lujo',
    summary:
      'Penthouse de 250 m² con terraza privada de 80 m². Vista 360° a la ciudad desde Reforma. Acabados de lujo europeo.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 18900000,
    priceLabel: 'MN 18,900,000',
    beds: 3,
    baths: 3,
    parking: 2,
    m2Built: 250,
    m2Land: null,
    age: 1,
    amenities: ['terraza', 'vista_ciudad', 'jacuzzi', 'gimnasio', 'estacionamiento'],
    address: 'Paseo de la Reforma 222 PH, Polanco',
    zone: 'Polanco',
    colony: 'Polanco',
    municipality: 'Cuauhtémoc',
    state: 'Ciudad de México',
    lat: 19.4328,
    lng: -99.1939,
    isFeatured: true,
    badges: ['Venta', 'Penthouse', 'Lujo'],
    highlights: ['Terraza 80 m²', 'Vista 360°', 'Acabados europeos'],
    photoCount: 16,
  },
  {
    slug: 'depto-roma-norte-art-deco-restaurado',
    title: 'Departamento art deco restaurado en Roma Norte',
    summary:
      'Depto de 2 recámaras en edificio histórico de 1950s restaurado. Pisos de mármol, techos altos, frente a Parque México.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 8750000,
    priceLabel: 'MN 8,750,000',
    beds: 2,
    baths: 2,
    parking: 1,
    m2Built: 140,
    m2Land: null,
    age: 75,
    amenities: ['pisos_marmol', 'parquet', 'vista_parque', 'techos_altos'],
    address: 'Calle Álvaro Obregón 180, Roma Norte',
    zone: 'Roma Norte',
    colony: 'Roma Norte',
    municipality: 'Cuauhtémoc',
    state: 'Ciudad de México',
    lat: 19.4198,
    lng: -99.1603,
    isFeatured: false,
    badges: ['Venta', 'Departamento', 'Art deco'],
    highlights: ['Frente a Parque México', 'Edificio histórico', 'Pisos mármol'],
    photoCount: 12,
  },
  {
    slug: 'casa-roma-norte-con-jardin',
    title: 'Casa con jardín en Roma Norte',
    summary:
      'Casa de 3 recámaras con patio interior y jardín tropical. Ideal para teletrabajo con estudio independiente. Tranquila y céntrica.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 11200000,
    priceLabel: 'MN 11,200,000',
    beds: 3,
    baths: 2,
    parking: 1,
    m2Built: 220,
    m2Land: 280,
    age: 8,
    amenities: ['jardin', 'estudio', 'patio_interior', 'estacionamiento'],
    address: 'Calle Medellín 42, Roma Norte',
    zone: 'Roma Norte',
    colony: 'Roma Norte',
    municipality: 'Cuauhtémoc',
    state: 'Ciudad de México',
    lat: 19.4190,
    lng: -99.1608,
    isFeatured: false,
    badges: ['Venta', 'Casa', 'Jardín'],
    highlights: ['Estudio independiente', 'Patio interior', 'Zona tranquila'],
    photoCount: 11,
  },
  {
    slug: 'depto-condesa-parque-espana',
    title: 'Departamento Condesa frente Parque España',
    summary:
      'Depto de 2 recámaras con balcón frente al Parque España. Modernizado, alberca común, rooftop con vista. Muy solicitado.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 7950000,
    priceLabel: 'MN 7,950,000',
    beds: 2,
    baths: 2,
    parking: 1,
    m2Built: 125,
    m2Land: null,
    age: 4,
    amenities: ['balcon', 'vista_parque', 'alberca', 'rooftop', 'estacionamiento'],
    address: 'Avenida Sonora 150, Condesa',
    zone: 'Condesa',
    colony: 'Condesa',
    municipality: 'Cuauhtémoc',
    state: 'Ciudad de México',
    lat: 19.4130,
    lng: -99.1732,
    isFeatured: false,
    badges: ['Venta', 'Departamento', 'Frente parque'],
    highlights: ['Frente Parque España', 'Rooftop con vista', 'Zona gastronómica'],
    photoCount: 13,
  },
  {
    slug: 'loft-condesa-moderno-dos-pisos',
    title: 'Loft moderno duplex en Condesa',
    summary:
      'Loft de 2 pisos con estudio abierto, aire industrial. Terraza privada, acabados contemporáneos. Perfecto para creativo digital.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 6480000,
    priceLabel: 'MN 6,480,000',
    beds: 1,
    baths: 1,
    parking: 1,
    m2Built: 110,
    m2Land: null,
    age: 3,
    amenities: ['loft', 'terraza', 'estudio_abierto', 'estacionamiento', 'aire_industrial'],
    address: 'Calle Tamaulipas 285, Condesa',
    zone: 'Condesa',
    colony: 'Condesa',
    municipality: 'Cuauhtémoc',
    state: 'Ciudad de México',
    lat: 19.4126,
    lng: -99.1728,
    isFeatured: false,
    badges: ['Venta', 'Loft', 'Moderno'],
    highlights: ['Duplex 2 pisos', 'Estilo industrial', 'Terraza privada'],
    photoCount: 12,
  },
  {
    slug: 'casa-coyoacan-colonial-frida-kahlo',
    title: 'Casa colonial en Coyoacán cerca Museo Frida Kahlo',
    summary:
      'Casa tradicional de 3 recámaras a 5 min caminando de Museo Frida Kahlo. Patio colonial, bien conservada, zona turística y artística.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 9600000,
    priceLabel: 'MN 9,600,000',
    beds: 3,
    baths: 2,
    parking: 1,
    m2Built: 210,
    m2Land: 260,
    age: 45,
    amenities: ['patio_central', 'jardin', 'estacionamiento', 'zona_historica'],
    address: 'Calle Allende 34, Coyoacán',
    zone: 'Coyoacán',
    colony: 'Coyoacán',
    municipality: 'Coyoacán',
    state: 'Ciudad de México',
    lat: 19.3500,
    lng: -99.1620,
    isFeatured: false,
    badges: ['Venta', 'Casa colonial', 'Histórica'],
    highlights: ['Cerca Museo Frida', 'Patio colonial', 'Zona artística'],
    photoCount: 10,
  },
  {
    slug: 'depto-del-valle-familiar-3-recamaras',
    title: 'Departamento familiar en Del Valle',
    summary:
      'Depto de 3 recámaras en zona familiar de Del Valle. Alberca común, cerca metro, escuelas de calidad. Muy bien ubicado.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 4980000,
    priceLabel: 'MN 4,980,000',
    beds: 3,
    baths: 2,
    parking: 2,
    m2Built: 135,
    m2Land: null,
    age: 6,
    amenities: ['alberca', 'cerca_metro', 'parque_infantil', 'estacionamiento'],
    address: 'Calle Dickens 102, Del Valle',
    zone: 'Del Valle',
    colony: 'Del Valle',
    municipality: 'Benito Juárez',
    state: 'Ciudad de México',
    lat: 19.3840,
    lng: -99.1645,
    isFeatured: false,
    badges: ['Venta', 'Departamento', 'Familiar'],
    highlights: ['Zona familiar', 'Cerca metro', 'Buenas escuelas'],
    photoCount: 9,
  },
]

// ── MÉRIDA, YUC (6 listings) ─────────────────────────────────────────────
const MERIDA: DemoListing[] = [
  {
    slug: 'casona-colonial-restaurada-merida-centro',
    title: 'Casona colonial restaurada en Centro Histórico',
    summary:
      'Casona de 1880 restaurada con 4 recámaras. Patio andaluz, techos altos, bien de patrimonio. Alquiler vacacional exitoso.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 14800000,
    priceLabel: 'MN 14,800,000',
    beds: 4,
    baths: 4,
    parking: 2,
    m2Built: 420,
    m2Land: 380,
    age: 143,
    amenities: ['patio_andaluz', 'techos_altos', 'bien_patrimonial', 'cocina_comercial'],
    address: 'Calle 47 No. 492, Centro Histórico',
    zone: 'Centro',
    colony: 'Centro',
    municipality: 'Mérida',
    state: 'Yucatán',
    lat: 20.9674,
    lng: -89.6230,
    isFeatured: true,
    badges: ['Venta', 'Casona colonial', 'Patrimonio'],
    highlights: ['Patio andaluz', 'Bien de patrimonio', 'Potencial alquiler vacacional'],
    photoCount: 14,
  },
  {
    slug: 'casa-merida-centro-piscina-patio-andaluz',
    title: 'Casa con piscina y patio andaluz en Centro',
    summary:
      'Casa de 3 recámaras con piscina privada. Patio andaluz con fuente, jardín tropical. Centro histórico a 3 cuadras.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 11500000,
    priceLabel: 'MN 11,500,000',
    beds: 3,
    baths: 3,
    parking: 2,
    m2Built: 280,
    m2Land: 320,
    age: 5,
    amenities: ['alberca', 'patio_andaluz', 'jardin_tropical', 'fuente', 'aire_acondicionado'],
    address: 'Calle 60 No. 287, Centro',
    zone: 'Centro',
    colony: 'Centro',
    municipality: 'Mérida',
    state: 'Yucatán',
    lat: 20.9682,
    lng: -89.6228,
    isFeatured: true,
    badges: ['Venta', 'Casa', 'Piscina'],
    highlights: ['Piscina privada', 'Patio andaluz', 'Centro histórico'],
    photoCount: 13,
  },
  {
    slug: 'local-comercial-paseo-montejo-merida',
    title: 'Local comercial en Paseo Montejo',
    summary:
      'Local de 150 m² en Paseo Montejo, la avenida más exclusiva. Ideal boutique, galería o consultorios. Gran visibilidad y tráfico.',
    operationType: 'renta_larga',
    propertyType: 'local_comercial',
    price: 32000,
    priceLabel: 'MN 32,000/mes',
    beds: null,
    baths: 2,
    parking: 0,
    m2Built: 150,
    m2Land: null,
    age: 8,
    amenities: ['frente_calle', 'aire_acondicionado', 'estacionamiento_cercano', 'recepcion'],
    address: 'Paseo Montejo 501, Paseo Montejo',
    zone: 'Paseo Montejo',
    colony: 'Paseo Montejo',
    municipality: 'Mérida',
    state: 'Yucatán',
    lat: 20.9722,
    lng: -89.6185,
    isFeatured: true,
    badges: ['Renta larga', 'Local comercial', 'Paseo Montejo'],
    highlights: ['Avenida exclusiva', 'Gran visibilidad', 'Tráfico garantizado'],
    photoCount: 10,
  },
  {
    slug: 'casa-itzimna-moderna-alberca',
    title: 'Casa moderna en Itzimná con alberca',
    summary:
      'Casa de 3 recámaras en Itzimná, zona residencial premium. Diseño moderno, alberca, jardín amplio, seguridad 24h.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 8900000,
    priceLabel: 'MN 8,900,000',
    beds: 3,
    baths: 3,
    parking: 2,
    m2Built: 260,
    m2Land: 380,
    age: 3,
    amenities: ['alberca', 'jardin', 'seguridad_24h', 'aire_acondicionado', 'cocina_integral'],
    address: 'Calle 27 No. 215, Itzimná',
    zone: 'Itzimná',
    colony: 'Itzimná',
    municipality: 'Mérida',
    state: 'Yucatán',
    lat: 20.9962,
    lng: -89.6154,
    isFeatured: false,
    badges: ['Venta', 'Casa moderna', 'Premium'],
    highlights: ['Zona residencial premium', 'Alberca', 'Seguridad 24h'],
    photoCount: 12,
  },
  {
    slug: 'casa-itzimna-familiar-3-recamaras',
    title: 'Casa familiar en Itzimná',
    summary:
      'Casa de 3 recámaras en Itzimná. Patio interior, buena inversión, zona en desarrollo. A 15 min del centro.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 6750000,
    priceLabel: 'MN 6,750,000',
    beds: 3,
    baths: 2,
    parking: 1,
    m2Built: 200,
    m2Land: 280,
    age: 7,
    amenities: ['patio_interior', 'jardin', 'estacionamiento'],
    address: 'Calle 12 No. 145, Itzimná',
    zone: 'Itzimná',
    colony: 'Itzimná',
    municipality: 'Mérida',
    state: 'Yucatán',
    lat: 20.9956,
    lng: -89.6160,
    isFeatured: false,
    badges: ['Venta', 'Casa familiar', 'Inversión'],
    highlights: ['Zona en desarrollo', 'Buena inversión', '15 min del centro'],
    photoCount: 10,
  },
  {
    slug: 'casa-boutique-garcia-gineres-merida',
    title: 'Casa boutique en García Ginerés',
    summary:
      'Casa de 2 recámaras diseño contemporáneo en García Ginerés. Terraza con vista, cocina integrada, acabados premium.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 5480000,
    priceLabel: 'MN 5,480,000',
    beds: 2,
    baths: 2,
    parking: 1,
    m2Built: 180,
    m2Land: 220,
    age: 2,
    amenities: ['terraza', 'cocina_integral', 'aire_acondicionado', 'estacionamiento'],
    address: 'Calle 33 No. 234, García Ginerés',
    zone: 'García Ginerés',
    colony: 'García Ginerés',
    municipality: 'Mérida',
    state: 'Yucatán',
    lat: 20.9758,
    lng: -89.6358,
    isFeatured: false,
    badges: ['Venta', 'Casa boutique', 'Contemporáneo'],
    highlights: ['Terraza con vista', 'Acabados premium', 'Diseño moderno'],
    photoCount: 11,
  },
]

// ── SAN MIGUEL DE ALLENDE, GTO (4 listings) ──────────────────────────────
const SMA: DemoListing[] = [
  {
    slug: 'casa-sma-vista-parroquia-centro',
    title: 'Casa colonial con vista a la Parroquia',
    summary:
      'Casa tradicional de 3 recámaras en Centro con vista a la Parroquia. Patio interior, escaleras de piedra, patrimonio cultural.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 12200000,
    priceLabel: 'MN 12,200,000',
    beds: 3,
    baths: 2,
    parking: 1,
    m2Built: 240,
    m2Land: 280,
    age: 50,
    amenities: ['patio_central', 'vista_parroquia', 'bien_patrimonial', 'escaleras_piedra'],
    address: 'Calle Mesones 12, Centro',
    zone: 'Centro colonial',
    colony: 'Centro',
    municipality: 'San Miguel de Allende',
    state: 'Guanajuato',
    lat: 20.9148,
    lng: -100.7459,
    isFeatured: true,
    badges: ['Venta', 'Casa colonial', 'Vista Parroquia'],
    highlights: ['Vista a la Parroquia', 'Patrimonio cultural', 'Centro histórico'],
    photoCount: 13,
  },
  {
    slug: 'casa-sma-patio-limonero-centro',
    title: 'Casa con patio y limonero en Centro',
    summary:
      'Casa de 3 recámaras con patio interior con limonero centenario. Atmosfera tranquila, buenos acabados, zona de galerías.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 9800000,
    priceLabel: 'MN 9,800,000',
    beds: 3,
    baths: 2,
    parking: 1,
    m2Built: 220,
    m2Land: 240,
    age: 35,
    amenities: ['patio_central', 'limonero', 'estacionamiento', 'tranquilo'],
    address: 'Calle de los Reyes 45, Centro',
    zone: 'Centro colonial',
    colony: 'Centro',
    municipality: 'San Miguel de Allende',
    state: 'Guanajuato',
    lat: 20.9150,
    lng: -100.7461,
    isFeatured: false,
    badges: ['Venta', 'Casa', 'Patio'],
    highlights: ['Patio con limonero', 'Zona de galerías', 'Tranquilo'],
    photoCount: 11,
  },
  {
    slug: 'casa-sma-colonial-dos-plantas',
    title: 'Casa colonial dos plantas en Centro',
    summary:
      'Casa de 4 recámaras en dos plantas. Escaleras de cantera, patio amplio, sala de estar principal. Bien conservada.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 11500000,
    priceLabel: 'MN 11,500,000',
    beds: 4,
    baths: 3,
    parking: 2,
    m2Built: 300,
    m2Land: 320,
    age: 60,
    amenities: ['patio_amplio', 'escaleras_cantera', 'sala_estar', 'estacionamiento'],
    address: 'Calle San Francisco 88, Centro',
    zone: 'Centro colonial',
    colony: 'Centro',
    municipality: 'San Miguel de Allende',
    state: 'Guanajuato',
    lat: 20.9146,
    lng: -100.7457,
    isFeatured: false,
    badges: ['Venta', 'Casa colonial', '2 plantas'],
    highlights: ['Dos plantas', 'Patio amplio', 'Bien conservada'],
    photoCount: 12,
  },
  {
    slug: 'casa-atascadero-moderna-vista',
    title: 'Casa moderna en Atascadero con vista',
    summary:
      'Casa contemporánea de 3 recámaras en Atascadero. Vista al valle, diseño abierto, terraza panorámica, privada segura.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 7650000,
    priceLabel: 'MN 7,650,000',
    beds: 3,
    baths: 2,
    parking: 2,
    m2Built: 240,
    m2Land: 360,
    age: 4,
    amenities: ['terraza', 'vista_valle', 'privada', 'seguridad', 'diseño_abierto'],
    address: 'Lote 5 Privada Atascadero, Atascadero',
    zone: 'Atascadero',
    colony: 'Atascadero',
    municipality: 'San Miguel de Allende',
    state: 'Guanajuato',
    lat: 20.9258,
    lng: -100.7351,
    isFeatured: false,
    badges: ['Venta', 'Casa moderna', 'Vista'],
    highlights: ['Vista al valle', 'Diseño contemporáneo', 'Privada segura'],
    photoCount: 10,
  },
]

// ── TULUM + PLAYA DEL CARMEN, QR (6 listings) ────────────────────────────
const TULUM_PLAYA: DemoListing[] = [
  {
    slug: 'depto-aldea-zama-eco-alberca',
    title: 'Departamento eco Aldea Zama con alberca',
    summary:
      'Depto de 2 recámaras en Aldea Zama, fraccionamiento eco-amigable. Alberca común, cero huella de carbono, a 10 min de playas.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 6980000,
    priceLabel: 'MN 6,980,000',
    beds: 2,
    baths: 2,
    parking: 1,
    m2Built: 115,
    m2Land: null,
    age: 2,
    amenities: ['alberca', 'eco_amigable', 'area_verde', 'estacionamiento', 'cercano_playas'],
    address: 'Lote 45 Calle Sagitario, Aldea Zama',
    zone: 'Aldea Zama',
    colony: 'Aldea Zama',
    municipality: 'Tulum',
    state: 'Quintana Roo',
    lat: 20.2076,
    lng: -87.4581,
    isFeatured: false,
    badges: ['Venta', 'Departamento', 'Eco'],
    highlights: ['Eco-amigable', '10 min de playas', 'Aldea Zama'],
    photoCount: 11,
  },
  {
    slug: 'casa-aldea-zama-selva-tulum',
    title: 'Casa en la selva Aldea Zama',
    summary:
      'Casa de 3 recámaras rodeada de selva en Aldea Zama. Piscina privada, aire acondicionado, comunidad exclusiva.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 8500000,
    priceLabel: 'MN 8,500,000',
    beds: 3,
    baths: 2,
    parking: 2,
    m2Built: 200,
    m2Land: 350,
    age: 3,
    amenities: ['alberca', 'selva', 'aire_acondicionado', 'privada', 'seguridad'],
    address: 'Lote 72 Aldea Zama, Tulum',
    zone: 'Aldea Zama',
    colony: 'Aldea Zama',
    municipality: 'Tulum',
    state: 'Quintana Roo',
    lat: 20.2072,
    lng: -87.4577,
    isFeatured: false,
    badges: ['Venta', 'Casa', 'Selva'],
    highlights: ['Rodeada de selva', 'Alberca privada', 'Comunidad exclusiva'],
    photoCount: 12,
  },
  {
    slug: 'lote-selva-tulum-800m2-construccion',
    title: 'Lote selvático 800 m² en Tulum Selva',
    summary:
      'Lote de 800 m² en zona Selva de Tulum. Servicios disponibles, permiso de construcción posible, perfecto para casa de playa.',
    operationType: 'venta',
    propertyType: 'terreno',
    price: 4200000,
    priceLabel: 'MN 4,200,000',
    beds: null,
    baths: null,
    parking: null,
    m2Built: null,
    m2Land: 800,
    age: null,
    amenities: ['servicios', 'selva', 'permiso_construccion'],
    address: 'Lote Calle 18, Selva Tulum',
    zone: 'Selva',
    colony: 'Selva',
    municipality: 'Tulum',
    state: 'Quintana Roo',
    lat: 20.1880,
    lng: -87.4720,
    isFeatured: false,
    badges: ['Venta', 'Lote', 'Selvático'],
    highlights: ['800 m² selva', 'Servicios disponibles', 'Casa de playa'],
    photoCount: 8,
  },
  {
    slug: 'casa-playacar-frente-mar-playa-del-carmen',
    title: 'Casa frente al mar en Playacar',
    summary:
      'Casa de 4 recámaras frente al mar en Playacar, Playa del Carmen. Piscina, jacuzzi, acceso directo a playa privada.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 16800000,
    priceLabel: 'MN 16,800,000',
    beds: 4,
    baths: 4,
    parking: 2,
    m2Built: 380,
    m2Land: 420,
    age: 5,
    amenities: ['alberca', 'jacuzzi', 'playa_privada', 'vista_mar', 'seguridad_24h'],
    address: 'Fraccionamiento Playacar Fase 2, Playa del Carmen',
    zone: 'Playacar',
    colony: 'Playacar',
    municipality: 'Solidaridad',
    state: 'Quintana Roo',
    lat: 20.6175,
    lng: -87.0775,
    isFeatured: true,
    badges: ['Venta', 'Casa', 'Frente mar'],
    highlights: ['Frente al mar', 'Playa privada', 'Playacar'],
    photoCount: 14,
  },
  {
    slug: 'depto-playacar-golf-course-playa',
    title: 'Departamento golf course en Playacar',
    summary:
      'Depto de 2 recámaras frente al campo de golf en Playacar. Vista al green, alberca común, a 5 min de Quinta Avenida.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 9750000,
    priceLabel: 'MN 9,750,000',
    beds: 2,
    baths: 2,
    parking: 1,
    m2Built: 140,
    m2Land: null,
    age: 4,
    amenities: ['vista_golf', 'alberca', 'cerca_quinta_avenida', 'estacionamiento'],
    address: 'Edificio Golf Playacar, Playacar',
    zone: 'Playacar',
    colony: 'Playacar',
    municipality: 'Solidaridad',
    state: 'Quintana Roo',
    lat: 20.6171,
    lng: -87.0771,
    isFeatured: false,
    badges: ['Venta', 'Departamento', 'Golf'],
    highlights: ['Vista golf course', '5 min Quinta Avenida', 'Alberca común'],
    photoCount: 12,
  },
  {
    slug: 'depto-playa-centro-5-min-quinta-avenida',
    title: 'Departamento en Centro a 5 min Quinta Avenida',
    summary:
      'Depto de 1 recámara en Centro de Playa del Carmen. A 5 min caminando de Quinta Avenida, comercios, restaurantes. Perfecto inversionista.',
    operationType: 'renta_larga',
    propertyType: 'departamento',
    price: 28000,
    priceLabel: 'MN 28,000/mes',
    beds: 1,
    baths: 1,
    parking: 1,
    m2Built: 75,
    m2Land: null,
    age: 3,
    amenities: ['cerca_quinta_avenida', 'amueblado', 'estacionamiento', 'wifi'],
    address: 'Calle 1 No. 125, Centro',
    zone: 'Centro',
    colony: 'Centro',
    municipality: 'Solidaridad',
    state: 'Quintana Roo',
    lat: 20.6296,
    lng: -87.0739,
    isFeatured: false,
    badges: ['Renta larga', 'Departamento', 'Centro'],
    highlights: ['5 min Quinta Avenida', 'Zona turística', 'Inversionista'],
    photoCount: 9,
  },
]

// ── QUERÉTARO, QRO (4 listings) ──────────────────────────────────────────
const QUERETARO: DemoListing[] = [
  {
    slug: 'casa-queretaro-centro-historico-colonial',
    title: 'Casa colonial en Centro Histórico Querétaro',
    summary:
      'Casa tradicional de 3 recámaras en Centro Histórico. Patio interior, bien de patrimonio, cerca Acueducto. Inversión turística.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 13500000,
    priceLabel: 'MN 13,500,000',
    beds: 3,
    baths: 3,
    parking: 2,
    m2Built: 320,
    m2Land: 300,
    age: 70,
    amenities: ['patio_central', 'bien_patrimonial', 'cerca_acueducto', 'techos_altos'],
    address: 'Calle 5 de Mayo 52, Centro Histórico',
    zone: 'Centro Histórico',
    colony: 'Centro',
    municipality: 'Querétaro',
    state: 'Querétaro',
    lat: 20.5890,
    lng: -100.3900,
    isFeatured: true,
    badges: ['Venta', 'Casa colonial', 'Patrimonio'],
    highlights: ['Centro Histórico', 'Bien de patrimonio', 'Inversión turística'],
    photoCount: 13,
  },
  {
    slug: 'depto-queretaro-centro-frente-acueducto',
    title: 'Departamento frente Acueducto en Centro',
    summary:
      'Depto de 2 recámaras con vista al Acueducto. Edificio nuevo, alberca, rooftop con vista panorámica, muy exclusivo.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 8200000,
    priceLabel: 'MN 8,200,000',
    beds: 2,
    baths: 2,
    parking: 1,
    m2Built: 130,
    m2Land: null,
    age: 1,
    amenities: ['vista_acueducto', 'alberca', 'rooftop', 'gimnasio', 'estacionamiento'],
    address: 'Avenida Corregidora 180, Centro',
    zone: 'Centro Histórico',
    colony: 'Centro',
    municipality: 'Querétaro',
    state: 'Querétaro',
    lat: 20.5892,
    lng: -100.3898,
    isFeatured: true,
    badges: ['Venta', 'Departamento', 'Acueducto'],
    highlights: ['Frente Acueducto', 'Rooftop panorámico', 'Edificio nuevo'],
    photoCount: 12,
  },
  {
    slug: 'casa-juriquilla-familiar-moderna',
    title: 'Casa familiar moderna en Juriquilla',
    summary:
      'Casa de 3 recámaras en Juriquilla. Alberca, área verde, seguridad 24h, escuelas cercanas. Zona residencial premium.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 6480000,
    priceLabel: 'MN 6,480,000',
    beds: 3,
    baths: 2,
    parking: 2,
    m2Built: 220,
    m2Land: 350,
    age: 4,
    amenities: ['alberca', 'area_verde', 'seguridad_24h', 'cerca_escuelas'],
    address: 'Avenida Juriquilla 500, Juriquilla',
    zone: 'Juriquilla',
    colony: 'Juriquilla',
    municipality: 'Querétaro',
    state: 'Querétaro',
    lat: 20.7052,
    lng: -100.4460,
    isFeatured: false,
    badges: ['Venta', 'Casa familiar', 'Juriquilla'],
    highlights: ['Zona residencial premium', 'Alberca', 'Escuelas cercanas'],
    photoCount: 11,
  },
  {
    slug: 'depto-juriquilla-campo-golf',
    title: 'Departamento cerca campo de golf Juriquilla',
    summary:
      'Depto de 2 recámaras junto al campo de golf. Vista al verde, amenidades Premium, fraccionamiento cerrado, tranquilo.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 5280000,
    priceLabel: 'MN 5,280,000',
    beds: 2,
    baths: 2,
    parking: 1,
    m2Built: 110,
    m2Land: null,
    age: 3,
    amenities: ['vista_golf', 'fraccionamiento', 'seguridad', 'estacionamiento', 'areas_verdes'],
    address: 'Edificio Golf Club, Juriquilla',
    zone: 'Juriquilla',
    colony: 'Juriquilla',
    municipality: 'Querétaro',
    state: 'Querétaro',
    lat: 20.7048,
    lng: -100.4456,
    isFeatured: false,
    badges: ['Venta', 'Departamento', 'Golf'],
    highlights: ['Campo golf cercano', 'Fraccionamiento cerrado', 'Tranquilo'],
    photoCount: 10,
  },
]

// ── GUADALAJARA, JAL (4 listings) ────────────────────────────────────────
const GUADALAJARA: DemoListing[] = [
  {
    slug: 'depto-providencia-vista-ciudad-gdl',
    title: 'Departamento en Providencia con vista ciudad',
    summary:
      'Depto de 2 recámaras en Providencia. Vista panorámica a la ciudad, alberca, gym, seguridad. Zona premium de Guadalajara.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 7500000,
    priceLabel: 'MN 7,500,000',
    beds: 2,
    baths: 2,
    parking: 1,
    m2Built: 125,
    m2Land: null,
    age: 3,
    amenities: ['vista_ciudad', 'alberca', 'gimnasio', 'seguridad', 'estacionamiento'],
    address: 'Avenida Niño Obrero 1200, Providencia',
    zone: 'Providencia',
    colony: 'Providencia',
    municipality: 'Guadalajara',
    state: 'Jalisco',
    lat: 20.7022,
    lng: -103.3925,
    isFeatured: false,
    badges: ['Venta', 'Departamento', 'Providencia'],
    highlights: ['Vista ciudad panorámica', 'Zona premium', 'Amenidades completas'],
    photoCount: 11,
  },
  {
    slug: 'casa-providencia-moderna-gdl',
    title: 'Casa moderna en Providencia',
    summary:
      'Casa de 3 recámaras en Providencia. Diseño contemporáneo, terraza, jardin, cochera. A 20 min del Centro Histórico.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 8800000,
    priceLabel: 'MN 8,800,000',
    beds: 3,
    baths: 2,
    parking: 2,
    m2Built: 240,
    m2Land: 300,
    age: 5,
    amenities: ['terraza', 'jardin', 'aire_acondicionado', 'estacionamiento'],
    address: 'Privada Arroyo Blanco 45, Providencia',
    zone: 'Providencia',
    colony: 'Providencia',
    municipality: 'Guadalajara',
    state: 'Jalisco',
    lat: 20.7018,
    lng: -103.3921,
    isFeatured: false,
    badges: ['Venta', 'Casa moderna', 'Providencia'],
    highlights: ['Diseño contemporáneo', 'Terraza y jardín', 'Zona segura'],
    photoCount: 12,
  },
  {
    slug: 'casa-boutique-lafayette-gdl',
    title: 'Casa boutique en Lafayette',
    summary:
      'Casa de 2 recámaras en Lafayette. Estilo bohemio, patio artístico, zona de galerías y cafeterías. Perfecta para creativo.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 6200000,
    priceLabel: 'MN 6,200,000',
    beds: 2,
    baths: 2,
    parking: 1,
    m2Built: 160,
    m2Land: 180,
    age: 8,
    amenities: ['patio_artistico', 'cerca_galerias', 'cafe_nearby', 'estacionamiento'],
    address: 'Calle 5 No. 1234, Lafayette',
    zone: 'Lafayette',
    colony: 'Lafayette',
    municipality: 'Guadalajara',
    state: 'Jalisco',
    lat: 20.6816,
    lng: -103.3738,
    isFeatured: false,
    badges: ['Venta', 'Casa boutique', 'Lafayette'],
    highlights: ['Zona bohemia', 'Cerca galerías', 'Estilo artístico'],
    photoCount: 10,
  },
  {
    slug: 'casa-chapalita-familiar-gdl',
    title: 'Casa familiar en Chapalita',
    summary:
      'Casa de 4 recámaras en Chapalita. Zona tranquila, excelentes escuelas, alberca pequeña, seguridad, perfecta familia.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 7950000,
    priceLabel: 'MN 7,950,000',
    beds: 4,
    baths: 3,
    parking: 2,
    m2Built: 280,
    m2Land: 380,
    age: 6,
    amenities: ['alberca', 'area_verde', 'seguridad', 'buenas_escuelas', 'tranquilo'],
    address: 'Calle Guachimontones 78, Chapalita',
    zone: 'Chapalita',
    colony: 'Chapalita',
    municipality: 'Guadalajara',
    state: 'Jalisco',
    lat: 20.6662,
    lng: -103.4092,
    isFeatured: false,
    badges: ['Venta', 'Casa familiar', 'Chapalita'],
    highlights: ['Excelentes escuelas', 'Zona tranquila', 'Alberca', 'Seguridad'],
    photoCount: 11,
  },
]

// ── MONTERREY / SAN PEDRO, NL (4 listings) ──────────────────────────────
const MONTERREY: DemoListing[] = [
  {
    slug: 'penthouse-san-pedro-valle-monterrey',
    title: 'Penthouse vista Valle en San Pedro Garza García',
    summary:
      'Penthouse de 3 recámaras con vista al Valle de Santa Catarina. Acabados lujo, terraza panorámica, edificio premium.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 14200000,
    priceLabel: 'MN 14,200,000',
    beds: 3,
    baths: 3,
    parking: 2,
    m2Built: 220,
    m2Land: null,
    age: 2,
    amenities: ['terraza_panoramica', 'vista_valle', 'jacuzzi', 'gimnasio', 'estacionamiento'],
    address: 'Avenida Paseo de Los Leones 500 PH, San Pedro',
    zone: 'San Pedro Garza García',
    colony: 'San Pedro',
    municipality: 'San Pedro Garza García',
    state: 'Nuevo León',
    lat: 25.6502,
    lng: -100.3999,
    isFeatured: true,
    badges: ['Venta', 'Penthouse', 'Premium'],
    highlights: ['Vista Valle', 'Terraza panorámica', 'Acabados lujo'],
    photoCount: 14,
  },
  {
    slug: 'casa-sierra-madre-san-pedro-monterrey',
    title: 'Casa vista Sierra Madre en San Pedro',
    summary:
      'Casa de 4 recámaras con vista a Sierra Madre Oriental. Piscina, jardín, terraza, zona residencial selecta.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 10500000,
    priceLabel: 'MN 10,500,000',
    beds: 4,
    baths: 3,
    parking: 2,
    m2Built: 320,
    m2Land: 420,
    age: 4,
    amenities: ['alberca', 'jardin', 'terraza', 'vista_sierra', 'seguridad_24h'],
    address: 'Paseo del Bosque 234, San Pedro',
    zone: 'San Pedro Garza García',
    colony: 'San Pedro',
    municipality: 'San Pedro Garza García',
    state: 'Nuevo León',
    lat: 25.6504,
    lng: -100.4001,
    isFeatured: false,
    badges: ['Venta', 'Casa', 'Vista Sierra'],
    highlights: ['Vista Sierra Madre', 'Alberca y jardín', 'Zona selecta'],
    photoCount: 13,
  },
  {
    slug: 'depto-calzada-san-pedro-monterrey',
    title: 'Departamento en Calzada de San Pedro',
    summary:
      'Depto de 2 recámaras en ubicación premium de Calzada. Alberca, gym, acceso comercial próximo. Inversión o vivienda.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 6950000,
    priceLabel: 'MN 6,950,000',
    beds: 2,
    baths: 2,
    parking: 1,
    m2Built: 120,
    m2Land: null,
    age: 3,
    amenities: ['alberca', 'gimnasio', 'seguridad', 'cerca_comercios', 'estacionamiento'],
    address: 'Avenida Calzada de San Pedro 1200, San Pedro',
    zone: 'San Pedro Garza García',
    colony: 'San Pedro',
    municipality: 'San Pedro Garza García',
    state: 'Nuevo León',
    lat: 25.6506,
    lng: -100.3997,
    isFeatured: false,
    badges: ['Venta', 'Departamento', 'Calzada'],
    highlights: ['Ubicación premium', 'Acceso comercial', 'Inversión/vivienda'],
    photoCount: 11,
  },
  {
    slug: 'depto-valle-oriente-torre-nueva-monterrey',
    title: 'Departamento Valle Oriente en torre nueva',
    summary:
      'Depto de 2 recámaras en Valle Oriente. Edificio nuevo, vista verde, acabados modernos, zona de negocios.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 5800000,
    priceLabel: 'MN 5,800,000',
    beds: 2,
    baths: 2,
    parking: 1,
    m2Built: 110,
    m2Land: null,
    age: 1,
    amenities: ['vista_verde', 'edificio_nuevo', 'gimnasio', 'estacionamiento', 'area_negocios'],
    address: 'Edificio Premium Valle Oriente, Valle Oriente',
    zone: 'Valle Oriente',
    colony: 'Valle Oriente',
    municipality: 'San Pedro Garza García',
    state: 'Nuevo León',
    lat: 25.6396,
    lng: -100.3015,
    isFeatured: false,
    badges: ['Venta', 'Departamento', 'Valle Oriente'],
    highlights: ['Torre nueva', 'Zona negocios', 'Acabados modernos'],
    photoCount: 10,
  },
]

// ── PUERTO VALLARTA, JAL (4 listings) ────────────────────────────────────
const VALLARTA: DemoListing[] = [
  {
    slug: 'casa-gringo-gulch-puerto-vallarta',
    title: 'Casa Gringo Gulch en Puerto Vallarta',
    summary:
      'Casa de 3 recámaras en Gringo Gulch. Vista al mar, piscina privada, escaleras a la playa, zona más exclusiva de PV.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 13800000,
    priceLabel: 'MN 13,800,000',
    beds: 3,
    baths: 3,
    parking: 1,
    m2Built: 280,
    m2Land: 320,
    age: 6,
    amenities: ['alberca', 'vista_mar', 'escaleras_playa', 'seguridad', 'jacuzzi'],
    address: 'Callejón del Agua 45, Gringo Gulch',
    zone: 'Centro',
    colony: 'Gringo Gulch',
    municipality: 'Puerto Vallarta',
    state: 'Jalisco',
    lat: 20.6157,
    lng: -105.2356,
    isFeatured: true,
    badges: ['Venta', 'Casa', 'Gringo Gulch'],
    highlights: ['Vista al mar', 'Escaleras a playa', 'Zona exclusiva'],
    photoCount: 13,
  },
  {
    slug: 'depto-marina-frente-vallarta',
    title: 'Departamento frente Marina en Puerto Vallarta',
    summary:
      'Depto de 2 recámaras frente Marina. Vista directa al mar, paseo marítimo a pie, tiendas y restaurantes próximos.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 9200000,
    priceLabel: 'MN 9,200,000',
    beds: 2,
    baths: 2,
    parking: 1,
    m2Built: 140,
    m2Land: null,
    age: 4,
    amenities: ['frente_marina', 'vista_mar', 'malecon_cercano', 'comercios_proximos'],
    address: 'Avenida México 1580, Marina',
    zone: 'Marina',
    colony: 'Marina',
    municipality: 'Puerto Vallarta',
    state: 'Jalisco',
    lat: 20.6537,
    lng: -105.2389,
    isFeatured: false,
    badges: ['Venta', 'Departamento', 'Marina'],
    highlights: ['Frente Marina', 'Vista al mar', 'Paseo marítimo a pie'],
    photoCount: 12,
  },
  {
    slug: 'penthouse-marina-vista-bahia-vallarta',
    title: 'Penthouse Marina con vista bahía en Vallarta',
    summary:
      'Penthouse de 3 recámaras en Marina. Vista panorámica a la bahía, terraza con jacuzzi, edificio 5 estrellas.',
    operationType: 'venta',
    propertyType: 'departamento',
    price: 12500000,
    priceLabel: 'MN 12,500,000',
    beds: 3,
    baths: 3,
    parking: 2,
    m2Built: 210,
    m2Land: null,
    age: 2,
    amenities: ['terraza', 'vista_bahia', 'jacuzzi', 'rooftop', 'gimnasio', 'concierge'],
    address: 'Torre Marina Vallarta PH, Marina',
    zone: 'Marina',
    colony: 'Marina',
    municipality: 'Puerto Vallarta',
    state: 'Jalisco',
    lat: 20.6533,
    lng: -105.2385,
    isFeatured: true,
    badges: ['Venta', 'Penthouse', 'Bahía'],
    highlights: ['Vista panorámica bahía', 'Jacuzzi en terraza', 'Edificio 5 estrellas'],
    photoCount: 15,
  },
  {
    slug: 'casa-conchas-chinas-frente-mar-vallarta',
    title: 'Casa frente al mar en Conchas Chinas',
    summary:
      'Casa de 3 recámaras en Conchas Chinas. Acceso a playa privada rocosa, vistas al Pacífico, zona residencial tranquila.',
    operationType: 'venta',
    propertyType: 'casa',
    price: 11800000,
    priceLabel: 'MN 11,800,000',
    beds: 3,
    baths: 3,
    parking: 2,
    m2Built: 260,
    m2Land: 300,
    age: 5,
    amenities: ['playa_privada', 'vista_pacifico', 'alberca', 'terraza', 'tranquilo'],
    address: 'Avenida de las Olas 189, Conchas Chinas',
    zone: 'Conchas Chinas',
    colony: 'Conchas Chinas',
    municipality: 'Puerto Vallarta',
    state: 'Jalisco',
    lat: 20.5882,
    lng: -105.2354,
    isFeatured: false,
    badges: ['Venta', 'Casa', 'Frente mar'],
    highlights: ['Playa privada rocosa', 'Vista Pacífico', 'Zona tranquila'],
    photoCount: 13,
  },
]

/**
 * Hash determinístico simple para indexar el pool por slug.
 */
function hashStr(s: string): number {
  let h = 0
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0
  return Math.abs(h)
}

/**
 * Pools de fotos por región (Wikimedia Commons, verificadas HTTP 200)
 */
const PHOTO_POOLS = {
  cdmx: [
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Archaeological_Museum%2C_Mexico_City_late_19th_century.jpg/1280px-Archaeological_Museum%2C_Mexico_City_late_19th_century.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Architectural_Detail_-_Avenida_Mexico_-_Condesa_District_-_Mexico_City_-_Mexico_%2815333803787%29.jpg/1280px-Architectural_Detail_-_Avenida_Mexico_-_Condesa_District_-_Mexico_City_-_Mexico_%2815333803787%29.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Art_Deco_Architecture_in_Condesa_District_-_Mexico_City_-_Mexico_%286480170637%29.jpg/1280px-Art_Deco_Architecture_in_Condesa_District_-_Mexico_City_-_Mexico_%286480170637%29.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Conjunto_Aristos_relief_in_Mexico_City.jpg/1280px-Conjunto_Aristos_relief_in_Mexico_City.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Mexican_Architecture.jpg/1280px-Mexican_Architecture.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Mexico%2C_Architecture%2C_ArmAg_%2811%29.JPG/1280px-Mexico%2C_Architecture%2C_ArmAg_%2811%29.JPG',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Mexico_City_Eagle_Details_%28223352027%29.jpeg/1280px-Mexico_City_Eagle_Details_%28223352027%29.jpeg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Municipal_organizations_in_Latin_America._Mexico_City_%281909%29_%2814597930680%29.jpg/1280px-Municipal_organizations_in_Latin_America._Mexico_City_%281909%29_%2814597930680%29.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/8/88/Old_architecture_Mexico_City.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Triple_turret_triumph_-_Mexico_City_7_Dec_2011.jpg/1280px-Triple_turret_triumph_-_Mexico_City_7_Dec_2011.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Glasses_at_Liverpool_Polanco%2C_Mexico_City_optical_department.jpg/1280px-Glasses_at_Liverpool_Polanco%2C_Mexico_City_optical_department.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Houseplants_at_Liverpool_Polanco%2C_Mexico_City_plant_department.jpg/1280px-Houseplants_at_Liverpool_Polanco%2C_Mexico_City_plant_department.jpg',
  ],
  merida: [
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Colonial_Facades_-_Merida_-_Mexico.jpg/1280px-Colonial_Facades_-_Merida_-_Mexico.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Esquina_de_El_Colonial%2C_M%C3%A9rida%2C_Yucat%C3%A1n_%2801%29.jpg/1280px-Esquina_de_El_Colonial%2C_M%C3%A9rida%2C_Yucat%C3%A1n_%2801%29.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/M%C3%A9rida_de_Yucat%C3%A1n_2023_-_11.jpg/1280px-M%C3%A9rida_de_Yucat%C3%A1n_2023_-_11.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/M%C3%A9rida_de_Yucat%C3%A1n_2023_-_12.jpg/1280px-M%C3%A9rida_de_Yucat%C3%A1n_2023_-_12.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/M%C3%A9rida_de_Yucat%C3%A1n_2023_-_2.jpg/1280px-M%C3%A9rida_de_Yucat%C3%A1n_2023_-_2.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/M%C3%A9rida_de_Yucat%C3%A1n_2023_-_3.jpg/1280px-M%C3%A9rida_de_Yucat%C3%A1n_2023_-_3.jpg',
  ],
  sma: [
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/ElGrito_SanMiguelDeAllende2019.jpg/1280px-ElGrito_SanMiguelDeAllende2019.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/SanMiguel_wooddoor2019.jpg/1280px-SanMiguel_wooddoor2019.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/San_Miguel_Viejo%2C_San_Miguel_de_Allende.jpg/1280px-San_Miguel_Viejo%2C_San_Miguel_de_Allende.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/San_Miguel_Viejo_%28San_Miguel_de_Allende%2C_Gto.%29.jpg/1280px-San_Miguel_Viejo_%28San_Miguel_de_Allende%2C_Gto.%29.jpg',
  ],
  tulum_playa: [
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Mexico_-_beach_by_Tulum%2C_2022.jpg/1280px-Mexico_-_beach_by_Tulum%2C_2022.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Tulum_Beach_Panorama.jpg/1280px-Tulum_Beach_Panorama.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Maya_ruins_at_Tulum_2023_-_beach.jpg/1280px-Maya_ruins_at_Tulum_2023_-_beach.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Ruins_at_Tulum%2C_QR_Mexico_2023.jpg/1280px-Ruins_at_Tulum%2C_QR_Mexico_2023.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Tulum_beach_and_huts_below_Mayan_ruins.jpg/1280px-Tulum_beach_and_huts_below_Mayan_ruins.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Tulum_maya_ruins_mexico_beach_%2821201181980%29.jpg/1280px-Tulum_maya_ruins_mexico_beach_%2821201181980%29.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Tulum_maya_ruins_mexico_beach_%2821363014686%29.jpg/1280px-Tulum_maya_ruins_mexico_beach_%2821363014686%29.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Bike_path%2C_Playa_del_Carmen%2C_Quintana_Roo%2C_Mexico.jpg/1280px-Bike_path%2C_Playa_del_Carmen%2C_Quintana_Roo%2C_Mexico.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Playa_del_Carmen%2C_Quintana_Roo%2C_Mexico_-_Centro_Mayo_2021_-_02.jpg/1280px-Playa_del_Carmen%2C_Quintana_Roo%2C_Mexico_-_Centro_Mayo_2021_-_02.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Cenote_Ik_Kil%2C_Yucatan%2C_Dec_2011_-_01.jpg/1280px-Cenote_Ik_Kil%2C_Yucatan%2C_Dec_2011_-_01.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Cenote_Zaci_Yucatan_2008.jpg/1280px-Cenote_Zaci_Yucatan_2008.jpg',
  ],
  queretaro: [
    'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Centro_Hist%C3%B3rico_de_Santiago_de_Quer%C3%A9taro_-_10.jpg/1280px-Centro_Hist%C3%B3rico_de_Santiago_de_Quer%C3%A9taro_-_10.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Centro_Hist%C3%B3rico_de_Santiago_de_Quer%C3%A9taro_-_31.jpg/1280px-Centro_Hist%C3%B3rico_de_Santiago_de_Quer%C3%A9taro_-_31.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Centro_historico_de_Queretaro%2C_calle_5_de_Mayo_-_panoramio.jpg/1280px-Centro_historico_de_Queretaro%2C_calle_5_de_Mayo_-_panoramio.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/4/4e/Acueducto-queretaro-1874.jpg',
  ],
  guadalajara: [
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Catedral_metropolitana_de_Guadalajara_07.jpg/1280px-Catedral_metropolitana_de_Guadalajara_07.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Catedral_metropolitana_de_Guadalajara_11.jpg/1280px-Catedral_metropolitana_de_Guadalajara_11.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Centro_hist%C3%B3rico_de_Guadalajara_%28Jalisco%29.jpg/1280px-Centro_hist%C3%B3rico_de_Guadalajara_%28Jalisco%29.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Edificio_Mulbar_-_Guadalajara%2C_Jalisco_01.jpg/1280px-Edificio_Mulbar_-_Guadalajara%2C_Jalisco_01.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Edificio_Mulbar_-_Guadalajara%2C_Jalisco_03.jpg/1280px-Edificio_Mulbar_-_Guadalajara%2C_Jalisco_03.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Guadalajara%2C_Jalisco%2C_Mexico_%282021%29_-_166.jpg/1280px-Guadalajara%2C_Jalisco%2C_Mexico_%282021%29_-_166.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Plaza_Tapat%C3%ADa%2C_Guadalajara_11.jpg/1280px-Plaza_Tapat%C3%ADa%2C_Guadalajara_11.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Plaza_Tapat%C3%ADa.jpg/1280px-Plaza_Tapat%C3%ADa.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Plaza_tapatia_panor%C3%A1mica.jpg/1280px-Plaza_tapatia_panor%C3%A1mica.jpg',
  ],
  monterrey: [
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Macroplaza_Monterrey_2022_-_12.jpg/1280px-Macroplaza_Monterrey_2022_-_12.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Macroplaza_Monterrey_2022_-_13.jpg/1280px-Macroplaza_Monterrey_2022_-_13.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Macroplaza_Monterrey_2022_-_7.jpg/1280px-Macroplaza_Monterrey_2022_-_7.jpg',
  ],
  vallarta: [
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/En_Busca_de_la_Raz%C3%B3n%2C_Malec%C3%B3n%2C_Puerto_Vallarta%2C_2014.jpg/1280px-En_Busca_de_la_Raz%C3%B3n%2C_Malec%C3%B3n%2C_Puerto_Vallarta%2C_2014.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/March_2023_in_Puerto_Vallarta%2C_Jalisco_-_029.jpg/1280px-March_2023_in_Puerto_Vallarta%2C_Jalisco_-_029.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Puerto_Vallarta%2C_Jalisco%2C_2025_-_177.jpg/1280px-Puerto_Vallarta%2C_Jalisco%2C_2025_-_177.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Puerto_Vallarta%2C_Jalisco%2C_2025_-_179.jpg/1280px-Puerto_Vallarta%2C_Jalisco%2C_2025_-_179.jpg',
  ],
}

function getRegionKey(s: DemoListing): string {
  const state = s.state.toLowerCase()
  if (state.includes('méxico')) return 'cdmx'
  if (state.includes('yucatán')) return 'merida'
  if (state.includes('guanajuato')) return 'sma'
  if (state.includes('quintana roo')) return 'tulum_playa'
  if (state.includes('querétaro')) return 'queretaro'
  if (state.includes('jalisco') && s.municipality.includes('Guadalajara')) return 'guadalajara'
  if (state.includes('jalisco') && s.municipality.includes('Vallarta')) return 'vallarta'
  if (state.includes('nuevo león')) return 'monterrey'
  return 'cdmx' // default
}

function buildPhotoUrls(s: DemoListing): string[] {
  const regionKey = getRegionKey(s) as keyof typeof PHOTO_POOLS
  const pool = PHOTO_POOLS[regionKey] || PHOTO_POOLS.cdmx
  const start = hashStr(s.slug) % pool.length
  return Array.from({ length: s.photoCount }, (_, i) => {
    return pool[(start + i) % pool.length]
  })
}

export default class extends BaseSeeder {
  public async run() {
    const agent = await User.query().where('role', 'publisher').first()
    const agentId = agent?.id ?? null

    const ALL_LISTINGS = [
      ...CDMX,
      ...MERIDA,
      ...SMA,
      ...TULUM_PLAYA,
      ...QUERETARO,
      ...GUADALAJARA,
      ...MONTERREY,
      ...VALLARTA,
    ]

    for (const s of ALL_LISTINGS) {
      const photoUrls = buildPhotoUrls(s)

      const listing = await Listing.updateOrCreate(
        { slug: s.slug },
        {
          slug: s.slug,
          title: s.title,
          summary: s.summary,
          operationType: s.operationType,
          propertyType: s.propertyType,
          price: s.price,
          priceLabel: s.priceLabel,
          beds: s.beds,
          baths: s.baths,
          parking: s.parking,
          m2Built: s.m2Built,
          m2Land: s.m2Land,
          age: s.age,
          amenities: s.amenities,
          address: s.address,
          zone: s.zone,
          colony: s.colony,
          municipality: s.municipality,
          state: s.state,
          lat: s.lat,
          lng: s.lng,
          status: 'published',
          isPremier: s.isFeatured,
          isFeatured: s.isFeatured,
          badges: s.badges,
          highlights: s.highlights,
          mediaCount: s.photoCount,
          coverImageUrl: photoUrls[0] ?? null,
          publishedAt: DateTime.now(),
          viewCount: 0,
          agentId,
          createdBy: agentId,
          bedsLabel: s.beds ? `${s.beds} rec.` : null,
          sizeLabel: s.m2Built
            ? `${s.m2Built} m² const.${s.m2Land ? ` · ${s.m2Land} m² terreno` : ''}`
            : s.m2Land
              ? `${s.m2Land} m² terreno`
              : null,
          sizeM2: s.m2Built ? Math.round(s.m2Built) : s.m2Land ? Math.round(s.m2Land) : null,
        }
      )

      await ListingPhoto.query().where('listing_id', listing.id).delete()
      for (const [i, photoUrl] of photoUrls.entries()) {
        await ListingPhoto.create({
          listingId: listing.id,
          url: photoUrl,
          sortOrder: i + 1,
          isCover: i === 0,
        })
      }
    }
  }
}
